// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Opalop.Infrastructure.Persistence;

#nullable disable

namespace Opalop.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OpalopDbContext))]
    [Migration("20260405074509_AddMosaicJobOpacity")]
    partial class AddMosaicJobOpacity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Opalop.Domain.Entities.MosaicJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CompletedTiles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("completed_tiles");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<byte>("Opacity")
                        .HasColumnType("smallint")
                        .HasColumnName("opacity");

                    b.Property<int>("PxFormat")
                        .HasColumnType("integer")
                        .HasColumnName("px_format");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResultPath")
                        .HasColumnType("text")
                        .HasColumnName("result_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalTiles")
                        .HasColumnType("integer")
                        .HasColumnName("total_tiles");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mosaic_jobs");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_mosaic_jobs_created_at");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("ix_mosaic_jobs_resource_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_mosaic_jobs_user_id_status");

                    b.ToTable("mosaic_jobs", (string)null);
                });

            modelBuilder.Entity("Opalop.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Quadrants")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("quadrants");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<string>("TilePath")
                        .HasColumnType("text")
                        .HasColumnName("tile_path");

                    b.Property<float>("TotalA")
                        .HasColumnType("real")
                        .HasColumnName("total_a");

                    b.Property<float>("TotalB")
                        .HasColumnType("real")
                        .HasColumnName("total_b");

                    b.Property<float>("TotalL")
                        .HasColumnType("real")
                        .HasColumnName("total_l");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_photos");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_photos_user_id")
                        .HasFilter("is_active = true");

                    b.HasIndex("UserId", "TotalL")
                        .HasDatabaseName("ix_photos_user_id_total_l")
                        .HasFilter("is_active = true");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("Opalop.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_resources");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_resources_user_id");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("Opalop.Domain.Entities.SocialConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_social_connections");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_social_connections_user_id_provider");

                    b.ToTable("social_connections", (string)null);
                });

            modelBuilder.Entity("Opalop.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keycloak_id");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<int>("TicketBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("ticket_balance");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("KeycloakId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_keycloak_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Opalop.Domain.Entities.MosaicJob", b =>
                {
                    b.HasOne("Opalop.Domain.Entities.Resource", "Resource")
                        .WithMany("MosaicJobs")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mosaic_jobs_resources_resource_id");

                    b.HasOne("Opalop.Domain.Entities.User", "User")
                        .WithMany("MosaicJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mosaic_jobs_users_user_id");

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Opalop.Domain.Entities.Photo", b =>
                {
                    b.HasOne("Opalop.Domain.Entities.User", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_photos_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Opalop.Domain.Entities.Resource", b =>
                {
                    b.HasOne("Opalop.Domain.Entities.User", "User")
                        .WithMany("Resources")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resources_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Opalop.Domain.Entities.SocialConnection", b =>
                {
                    b.HasOne("Opalop.Domain.Entities.User", "User")
                        .WithMany("SocialConnections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_connections_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Opalop.Domain.Entities.Resource", b =>
                {
                    b.Navigation("MosaicJobs");
                });

            modelBuilder.Entity("Opalop.Domain.Entities.User", b =>
                {
                    b.Navigation("MosaicJobs");

                    b.Navigation("Photos");

                    b.Navigation("Resources");

                    b.Navigation("SocialConnections");
                });
#pragma warning restore 612, 618
        }
    }
}
